evanphx/json-patch

- merge.go
- merge_test.go
Before prune, test fails with:
```
--- FAIL: TestMergePatchNilDoc (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x45cf31]
goroutine 7 [running]:
testing.func·006()
/home/mike/.gvm/gos/go1.4/src/testing/testing.go:441 +0x181
_/home/mike/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/evanphx/json-patch.(*lazyNode).intoDoc(0x0, 0x6575a0, 0x0, 0x0)
/home/mike/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/evanphx/json-patch/patch.go:64 +0x31
_/home/mike/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/evanphx/json-patch.merge(0x0, …
```
> fix nil pointer dereference panic and add unit test that was failing

- patch.go
- patch_test.go
I ran into this when a patch document had a `test` op referencing a non-existent field.
> avoid nil dereference when testing values that do not exist

- merge.go
- merge_test.go
Previously, any pair of objects used to create a merge patch which had an inner array would result in a non-empty patch even if the two objects were completely identical.
> Add detection of unchanged arrays within objects.

- patch.go
- patch_test.go
Currently, any attempt to apply a patch that either adds a null value or replaces an existing value with a null one will cause a panic. This change fixes the panic by adding support for applying patches with null values.
> Support applying patches that contain null values

- merge.go
- merge_test.go
When merging to empty arrays, not null but empty arrays should be the result. This PR fixes the variable initialization of the result array to initialize no matter if the incoming array has elements or not. Includes a unit test for this case.
> Fix merge of existing array to empty array

- README.md
IETF RFC 7386 was superseded by RFC 7396.
> Link to current version of JSON Merge Patch RFC.

- patch.go
- patch_test.go
Another fix for path encoding - missed in previous PR.
Would appreciate quick turnaround on this as well if possible so can update a
couple of projects (kubernetes & openshift) that use this library.
> Respect path encoding in find object

- patch.go
Fixes a 1-character typo in the error message.  ;-)
> Fixes typo in error message string

- patch.go
- patch_test.go
This prevents a `slice bound out of range` panic when parsing an invalid
json patch where the path key is missing or the path value is empty
string or doesn't include `/`.
Fix https://github.com/kubernetes/kubernetes/issues/40218
> Prevent slice out of bound panic on invalid patch

- patch.go
- patch_test.go
While fixing #35 I found a couple of gofmt and golint issues that I wanted to cleanup.
Most notably I removed the const `LeftBrace` and just used the the `'['` char literal as that is more clear than a byte variable with the value `91` IMO :)
I assume no one is depending on this const outside of this library.
> gofmt and golint fixes

- patch.go
- patch_test.go
* Checked if a key exists in doc before replacing
* Added unit tests to BadCase
Resolves: [#40](https://github.com/evanphx/json-patch/issues/40)
Opened the pull request just in case you decide #40 is a bug. Please close it if you think it is not.
> Check target location for 'Replace' before replacing value

- cmd/json-patch/file_flag.go
- cmd/json-patch/main.go
I'm open to changing the implementation around a bit. The CLI approach makes it very handy to do e.g.:
```
~> cat doc.json
{
"foo": "bar"
}
~> cat patch.json
[
{"op":"add","path":"/baz","value":"quux"}
]
~> cat doc.json | json-patch -o patch.json
{"baz":"quux","foo":"bar"}
```
> Add cmd/ for consuming json-patch via CLI

- patch.go
- patch_test.go
This addresses the issue raised in issue https://github.com/evanphx/json-patch/issues/43.
The `tl;dr` of it the PR is to allow utilizing the `add` operation while specifying a valid negative index.
Note: I was not sure whether `func (d *partialArray) add(...) error` ought to panic or return an error. The reason I was unsure is because, _currently_, if you try to use an invalid positive array index it causes a runtime panic. I ended up have it returning an error in case an invalid negative index is used. I can change that if you would prefer.
Thanks! Let me know if you have any feedback.
Signed-off-by: Curtis La Graff <curtis@amberengine.com>
> fixed negative array index bug

- merge.go
- merge_test.go
When the value type is nil, it should be considered as equal.
> fix bug on matchesValue for nil type

- patch.go
- patch_test.go
Addresses the nil-pointer issue of `tryDoc` and `tryAry`.
Inspired by [schylek's PR #49 ](https://github.com/evanphx/json-patch/pull/49).
Also adds a couple extra nil-pointer checks for `lazyNode`.
However, because how everything is currently coded, I don't see an avenue for `intoDoc()`, `intoAry()`, or `compact()` to actually _have_ nil pointers to the `n.raw` property. So this was mostly "future-proofing" in case this ever changes. I can remove these extra checks or change the error messages if you would like 👍.
Doesn't modify the license.
> add nil-pointer checks to avoid runtime panics

- merge.go
- merge_test.go
Hello! 👋 
This PR attempts to tackle the problem @sh0umik brought up in [his PR (#48)](https://github.com/evanphx/json-patch/pull/48):
> Previously if we want to Create a Merge patch with a JSON Array then we would have got Invalid JSON
This PR fixes that issue. It allows users to use `CreateMergePatch` both with normal JSON documents, _as well as_ arrays of JSON documents.
Furthering the other PR, this one cleans up the code a bit more by splitting up `CreateMergePatch`'s internals into separate functions. It also adds a few extra tests and improves some of the docstrings.
Lastly, I also fixed some test names . Many of the tests were `TestMergePatch` when they should have been `TestCreateMergePatch` to mirror the actual function name.
---
Lastly, @evanphx you mentioned the following, …
> Allow arrays for CreateMergePatch

- patch.go
- patch_test.go
There happened a panic error in kubernetes seem because it.
https://github.com/kubernetes/kubernetes/issues/64291
> fix check idx index

- patch.go
- patch_test.go
The current code does not allow a null value to be replaced although there doesn't seem to be any test support for this.  So far as I can tell from the spec, a null is a legitimate json value that can be replaced by another value.
I added a few extra tests for other related cases as well just to prevent regressions.
> Allow replacement of null values

- patch.go
- patch_test.go
Without this change, the following code would panic:
```
package main
import (
"fmt"
jsonpatch "github.com/evanphx/json-patch"
)
func main() {
original := []byte(`{"name": "John", "age": 24, "height": 3.21}`)
patchJSON := []byte(`[
{"op": "test", "path": "/name"}
]`)
patch, err := jsonpatch.DecodePatch(patchJSON)
if err != nil {
fmt.Printf("decode %v\n", err)
return
}
modified, err := patch.Apply(original)
if err != nil {
fmt.Printf("aplly %v\n", err)
return
}
fmt.Printf("Original document: %s\n", original)
fmt.Printf("Modified document: %s\n", modified)
}
```
> fix test panic

- README.md
- patch.go
- patch_test.go
Otherwise the operation in the new test case can exhaust system memory.
> Adding a size limit when making array

- patch.go
- patch_test.go
Otherwise the added test case can cause a stack overflow.
I have considered adding a loop detection before doing the deep copy, but given that the `lazyNode` is lazily initializing, I think blindly deep copying is acceptable.
@evanphx
> In "copy" operation, deep copy the source container to prevent loops

- patch.go
- patch_test.go
See https://tools.ietf.org/html/rfc6902#section-4.5:
```
"copy" ... is functionally identical to an "add" operation at the target location using the value specified in the "from" member.
```
(The first commit is #71)
> Copy should add, not replace

- README.md
- patch.go
- patch_test.go
(Please review #74 first, sorry for messing up the order)
According to the RFC, "move" should `functionally identical to a "remove" operation on the "from" location, followed immediately by an "add" operation at the target location with the value that was just removed`. The library was doing a "remove" followed by a "replace" (i.e., set). The first commit fixed that.
The second commit removed the sanity check on the index in `partialArray.set()`, because `set` is now only called from `replace`, where the index must exist.
The second commit also removed the `ArraySizeAdditionLimit`, because the "move" and "copy" operation now can only at most increase array size by 1.
The third commit removed the `ArraySizeLimit`. See the commit message for why it's not useful anymore.
Thank you, @evanphx.
> "move should functionally equal to "remove" followed by "add"

- patch.go
This change enables users to inspect individual `Operation` fields.
For example, if a user wishes to implement security policies that must analyze `Patch` in detail before applying them, they might want to check each `path` field and determine if a given `Operation` is permitted by their security policy.
> Expose Operation with accessor methods

- merge.go
- merge_test.go
The matchesValue function, in the worst case, has exponential time complexity (for deeply nested maps). This fix should make things operate in time linear to the number of objects compared. 
Tests added: I've added some benchmark tests to justify the change. The tests generate a number of nested maps which creates an exponential number of nested map objects, given some input `n`. More precisely, the helper function generates 2^(n+1)-1 objects. 
We can see that with the original function, the growth does not increase linearly with the number of objects:
```
go test -bench=.                                                                                                                 1 ↵
goos: linux
goarch: amd64
pkg: github.com/evanphx/json-patch
BenchmarkMatchesValue1/objectCount=3-6 …
```
> check lengths of maps and recurse over only one if it is necessary

- patch.go
- patch_test.go
If SupportNegativeIndices is false then a negative indicie will cause a panic.
This regression was introduced in: fcd53eccb4f88d7e54b742358017d72c9b34ae44
Before that change we always checked the validity of the negative index.
> Fix panic when SupportNegativeIndices is false

- patch.go
- patch_test.go
There's a bug that makes Equal({"foo": "bar"}, {"foo": "bar", "baz": "qux"}) return true. This pr contains fix.
> Equality comparison bug fix

- patch.go
- patch_test.go
A "replace" patch operation referencing a key that does not exist in the target object are currently being accepted; ultimately becoming an "add" operation on the target object. This is incorrect per the specification:
From https://tools.ietf.org/html/rfc6902#section-4.3 section about
"replace":
The target location MUST exist for the operation to be successful.
This corrects the behavior by returning an error in this situation.
📎 https://github.com/evanphx/json-patch/issues/78
> Conform to RFC6902 replacement semantics

- README.md
- patch.go
- patch_test.go
I think this should fix #88 
I also added more tests for the `Equals()` function and tried to make it more consistent with the other test functions.
> Fix nil pointer dereference when comparing null to actual value in Equals()

- .travis.yml
- go.mod
- go.sum
- v5/cmd/json-patch/file_flag.go
- v5/cmd/json-patch/main.go
- v5/errors.go
- v5/go.mod
- v5/go.sum
- v5/merge.go
- v5/merge_test.go
- v5/patch.go
- v5/patch_test.go
ref: #98 
I also encountered that the go.mod does not actually require all dependencies, a `go build ./...` in each module updated the `go.mod`. This is how the "correct module requirements" commit was generated. 
I think this will still require a semver git tag afterwards
> add module v5

- patch.go
- patch_test.go
Related to https://github.com/containerd/cri/pull/1551#discussion_r465789692
Pull request https://github.com/evanphx/json-patch/pull/85 introduced a potentially breaking change, and (see the discussion on https://github.com/kubernetes/kubernetes/pull/91622#issuecomment-642781591) resulted in Kubernetes to hold-back this change in their dependencies. Given that this change can be considered a breaking change, it should probably have warranted a major version bump (to stick with SemVer).
Now that this project has a v5.x release, it should be possible to revert the change for v4.x. Consumers of this package that want to opt-on to the breaking change can update their dependency to use the v5 module, and consumers that are not (yet) ready to opt-in can continue using the v4.x releases until …
> Revert "Conform to RFC6902 replacement semantics" for v4.x

- merge.go
- merge_test.go
- v5/merge.go
- v5/merge_test.go
The existing matchesValue map comparison treats missing keys and nil values equivalently, which means it can return true for maps that are not actually equal
cc @logicalhan
> Fix map comparison of nil values and missing keys

- LICENSE
Add a missing comma according to the official BSD-3-Clause templates.
Resource: https://opensource.org/licenses/BSD-3-Clause
This is important in order to be compatible with the official template to avoid having LICENCE detectors failing to match the LICENCE like in https://github.com/elastic/beats/pull/18817#discussion_r432321740
cc: @evanphx
> Update LICENCE to fix minor typo

- go.mod
- go.sum
As noted in https://github.com/evanphx/json-patch/issues/98, the presence of a go.mod file in the root of the module in tagged semantic versions >= v2.x means go module consumers cannot address v4.x releases using semantic versions
For example, the recently tagged v4.8.0 has to be referred to as `v0.0.0-20200808040245-162e5629780b`, directly referencing the git SHA.
https://github.com/evanphx/json-patch/pull/100 resolved this for v5+, but removing the go.mod in the module root would allow v4.x consumers to resume referencing semantic version.
If this was merged and a v4.9.0 release tagged, consumers could do `go get github.com/evanphx/json-patch@v4.9.0` and record the tagged release in their go.mod files correctly.
This is more of a tidyness issue than a functional one (it makes the …
> Remove 4.x go.mod to make semantic versions addressable by tag

- README.md
- v5/patch.go
- v5/patch_test.go
* Implement ApplyWithOptions
* Implement ApplyWithOptions unit tests
* Fix compareJSON to allow comparison of array containers
* Fix previously incorrect "copy" operation tests
Closes #117.
> Introduce ApplyWithOptions

- v5/go.sum
- v5/merge.go
- v5/merge_test.go
- v5/patch.go
- v5/patch_test.go
Rather than using a `map[string]*lazyNode` for the doc (object) nodes, this is changed to use a rich type with both a map and an array of key-value pairs, and custom `MarshalJSON` and `UnmarshalJSON` functions.
> Fixes evanphx/json-patch#128 - custom marshalling for doc nodes

- merge.go
- merge_test.go
Fixes https://github.com/evanphx/json-patch/issues/132  (case for kubernetes https://github.com/kubernetes/kubernetes/issues/98080)
> Preserve "null" values in arrays

- v5/patch.go
We are using `%s` but the input is not a string. This can result in bad error messages, for example https://go.dev/play/p/NoimdDgOdDR
> Fix invalid sprintf

- v5/patch.go
- v5/patch_test.go
Pre-flight Patch validation in DecodePatch
> Pre-flight DecodePatch validation: Issue #177

- v5/patch.go
- v5/patch_test.go
> Compare strings after decoding them to handle unicode correctly. Fixes #172

- v5/merge.go
- v5/patch.go
> Always use UseNumber() to avoid float64 lossyness

- v5/merge.go
- v5/merge_test.go
- v5/patch.go
- v5/patch_test.go
> Handle null correctly when introduced by replace. Fixes #171

- v5/patch.go
> Validate that the partialDoc is decoded correctly

- v5/internal/json/encode.go
- v5/merge.go
- v5/patch.go
> Add option to control if the output is HTMLEscaped

- README.md
This aligns with the module declaration in go.mod.
> Drop the reference to gopkg.in for v5

- patch.go
- v5/go.mod
- v5/go.sum
- v5/patch.go
fix: https://github.com/evanphx/json-patch/issues/205
> remove unmaintained errors pkg(github.com/pkg/errors)
